### ISSUE TITLE
Error when running tests as per the docs

### ISSUE THREAD

**Issue by jonas089** [Electron-Labs/ed25519-circom#149]
I get this error in the circom-tester:

  1) ED25519 verifcation test
       When testing against the RFC test vector
         should verify correctly:
     LinkError: WebAssembly.instantiate(): Import #1 module="runtime" function="printErrorMessage" error: function import requires a callable
      at builder (node_modules/circom_tester/wasm/witness_calculator.js:19:40)
      at async wasm_tester (node_modules/circom_tester/wasm/tester.js:60:16)
      at async Context.<anonymous> (test/ed25519verfication.test.js:11:19)

is this known / is there a fix?

**Comment by jonas089** [comment]
Found the solution: Use the latest version of circom_tester
